In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [84]:
df = pd.read_csv('HealthData.csv') 
print("Data Shape:", df.shape) 
print(df.head())

Data Shape: (10000, 4)
           0   1          2   3
0  98.188214  80  99.749348  90
1  98.809898  74  99.346196  98
2  98.249848  78  99.631931  91
3  98.570041  77  99.523255  96
4  98.637673  72  98.974869  94

In [85]:
df.describe()

                  0            1             2             3
count  10000.000000  10000.00000  10000.000000  10000.000000
mean      97.740490     91.42520     95.243587     82.991400
std        2.182264     17.50997      3.984716      7.832807
min       94.000464     60.00000     85.003689     70.000000
25%       95.998633     76.00000     92.046497     77.000000
50%       98.077522     94.00000     96.738618     82.000000
75%       99.121507    106.00000     98.726657     89.000000
max      102.497957    120.00000     99.999741    100.000000

In [91]:
# Feature Matrix 
x_orig = df[['0','1','2']]

# Data labels 
y_orig = df['3'] 

print("Shape of Feature Matrix:", x_orig.shape) 
print("Shape Label Vector:", y_orig.shape)

Shape of Feature Matrix: (10000, 3)
Shape Label Vector: (10000,)

In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_orig, y_orig, test_size=0.2, random_state=10)

In [93]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [94]:
coeff_df = pd.DataFrame(regressor.coef_, x_orig.columns, columns=['Coefficient'])
coeff_df

   Coefficient
0     0.028235
1    -0.086130
2     1.015230

In [95]:
y_pred = regressor.predict(X_test)

In [96]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

      Actual  Predicted
937       90  88.765012
9355      72  72.514357
2293      84  82.399626
192       90  88.738322
8675      72  80.234265
53        98  87.883085
9596      76  74.609336
265      100  88.084151
984       98  88.379986
9793      78  72.914311
4737      89  86.201747
4691      90  90.246664
6016      84  79.030122
5376      84  87.003098
9366      79  72.997474
2481      81  83.464990
3909     100  87.151114
7533      78  78.172694
212       97  87.728200
1461      83  85.946851
9069      70  76.242757
3519      90  85.694522
2933      86  84.535169
9122      77  74.597800
209       95  88.477165
1865      88  87.345864
5481      76  88.395651
6128      81  77.299432
3449      95  87.283372
8888      72  76.984497
...      ...        ...
4464      88  86.505328
9240      74  70.904174
7372      72  79.677283
5149      82  89.319196
7472      77  78.239353
3151      98  86.376716
3302     100  85.045177
8017      76  76.682708
7380      80  76.654519
9284      74  76.367067
2062      81  82.964275
5366      82  88.650637
952       97  87.130044
7445      79  76.792457
2315      87  87.422387
5921      76  86.874062
1931      83  89.482550
934       98  87.747652
150       98  88.835242
6551      78  77.488685
6263      78  79.147921
9396      80  71.169522
6026      82  77.475788
6754      82  79.031288
3988      92  83.807985
5624      84  89.731587
6005      81  80.294417
987       98  88.373202
6152      84  77.790875
2092      85  85.556971

[2000 rows x 2 columns]

In [97]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 4.774722708343328
Mean Squared Error: 35.21316866582141
Root Mean Squared Error: 5.934068474985893